### ISSUE TITLE
Cant Claim Komodo Rewards...Get Errot

### ISSUE THREAD

**Issue by yogymon** [atomiclabs/ledger-kmd-reward-claim#21]
Error
Bitcoin JSON-RPC: Request Error: connect ECONNREFUSED 127.0.0.1:8232

Updated firmware.  Wondering if i'm doing something wrong.

Thanks!

**Comment by GandalfDerWeisse** [comment]
pretty sure that i had the same problem. so i updated my ledger nano s from 1.5.5 to 1.6.0, and now i got the same issue as #22

**Comment by ghost** [comment]
Error
Bitcoin JSON-RPC: Request Error: connect ECONNREFUSED 127.0.0.1:8232
<img width="634" alt="Снимок экрана 2020-02-27 в 09 59 12" src="https://user-images.githubusercontent.com/18265958/75419992-0d11a900-5948-11ea-91ff-3a4b37f6ccca.png">

**Comment by lukechilds** [comment]
Anytime you see that error it means the insight server is down. Normally due to `komodod` crashing.

I've just restarted the daemon and it seems to be working now.

I'm not really involved with this project much anymore so hadn't noticed it was down. @jorian do you want to take over access of the Insight server or is there someone else in-charge of sysadmin stuff you want me to talk to?

**Comment by GandalfDerWeisse** [comment]
unfortunately, it still doesn't work for me.. i still got that #22 issue
