### ISSUE TITLE
"Ledger device is unavailable" error

### ISSUE THREAD

**Issue by il051** [atomiclabs/ledger-kmd-reward-claim#8]
Hi there,

I tried to use this app for the first time to claim my reward for Komodo I'm holding on Ledger Nano S (latest firmware version 1.5.5). I followed the instructions and when a new window "scanning blockchain for rewards" opened, after 15-20 seconds of waiting I got the error message saying "Ledger device is unavailable", which is strange because meanwhile I got question on my Ledger device asking "Export public key?". I guess it means it recognizes my device, but the message says it doesn't so I'm confused. Komodo app on my Ledger is the latest version 1.3.8. 
I'm using Chrome (version 73.0.3683.86, official build, 64-bit) and Windows 7.
Any idea what could be wrong?

http://i65.tinypic.com/2jcam1k.png

**Comment by lukechilds** [comment]
This is a known issue, it's caused by Chrome changing the way they communicate with U2F devices which is how it also communicates with the Ledger.

Ledger are aware of the issue and will release new apps for Ledger devices to resolve the issue.

In the meantime, if you use Opera instead of Chrome, that should resolve the issue. Or alternatively you can use Firefox if you follow the instructions here: https://github.com/atomiclabs/ledger-kmd-reward-claim/issues/1

**Comment by il051** [comment]
I tried the same in Opera and it worked without any issues. Thank you for your support, you definitelly deserve your 5%. :)
